### PR TITLE
Organizing

### PR DESCRIPTION
**Pull request by defnoob**
The first commit is a must, but I'm not sure whether remove the .classpath and .project would affect things, therefore I need someone to check this branch before accepting the pull request. Also you will need to reconfigure the path to your respective native OS folder for lwjgl.

### CODE REVIEW

**Comment by peace-4-you** [comment]
It removes the Slick2D and Maven dependencies. Is this intentional ?

**Comment by defnoob** [comment]
What do you mean with removing the dependencies?
This pull request was orginally intended for master, but the devbranch could use it as well since it's more of an organizational thing.

**Comment by peace-4-you** [comment]
When I load the project into Eclipse, I have to reconfigure Maven and add Slick2D to the project again. 

Since everybody is going to work from the "development" branch anyways, I suggest we keep the change to that branch only. We can then PR into master later

**Comment by defnoob** [comment]
You need to run as Maven install before you start.

That's what maven is for.

**Comment by mauricewillemsen** [comment]
For me the master branch worked directly when deleted everything and loaded it, doesn't need to install maven or set slick2d

**Pull request merged**
