### PR TITLE
add easy, normal, hard difficulty modes

### PR DESCRIPTION
**Pull request by calvinnhieu**

### CODE REVIEW

**Comment by calvinnhieu** [comment]
TODO:
- logging
- tests

**Review by mauricewillemsen — APPROVED** [review]
Well done! I like the implementation of it. It really does make it more difficult

**Comment by defnoob** [comment]
Looks good, just need to fix merge conflicts.

**Review by winer-bao — APPROVED** [review]
Great work! Just a question: Is it possible to add new tests for the new code? (To test GameDifficulty)

**Comment by calvinnhieu** [comment]
@peace-4-you Definitely, I'll write some now

**Comment by mauricewillemsen** [comment]
Im sorry, some new merge errors occured after merged screenstats pr. should be simple to fix.

**Comment by calvinnhieu** [comment]
@mauricewillemsen no worries

**Pull request merged**
