### PR TITLE
PlayerNames at restart,

### LINKED ISSUE #104: Restart with default name
When you click on restart, your name is initially null(for a frame) and then it changes to Player1 and not the name that you have entered the first time. When you go to main menu and then play a new game, your old name is still there in the namefield.

### PR DESCRIPTION
**Pull request by mauricewillemsen**
Fixes:
Same Player names when restart;
Standard Player names when loading NameScreens again.
Fixed non writable textfield due to strange slick2d textfield error. 
Fixed #104

### CODE REVIEW

**Comment by defnoob** [comment]
Does indeed fix the name on restart issue,  but names seem to sometimes switch when you restart in a 2player game?

**Comment by peace-4-you** [comment]
Yeah, I see the issue Jason pointed out. E.g. in defeat screen in 2P mode, the names are switched. 

Scenario:
Player 1 is called Frank. Player 2 is called John. Both player lose with Frank get a score of 60 and John a score of 30. 
DefeatScreen shows John 60 point and Frank 30 points.

**Comment by mauricewillemsen** [comment]
No the second player is the one controlling with asdw instead off arrows. and because that keys are on the left. The left screen is for player 2 in my opinion

**Comment by peace-4-you** [comment]
> The left screen is for player 2 in my opinion

Ohh I see, that might be a bit confusing. But no big deal

**Comment by mauricewillemsen** [comment]
Yeah i understand, but otherwise the keys are confusing ;)

**Pull request merged**
