### PR TITLE
Achievements implemented.

### PR DESCRIPTION
**Pull request by justino10950**
Implemented the achievements and tests. Getting pretty good test coverage results. Except for the AchievementsScreen class which isnt tested.

### CODE REVIEW

**Comment by peace-4-you** [comment]
I'm a master after 1 win ?

**Comment by justino10950** [comment]
haha is fixed in the merge commit :p

**Review by caliangxie — CHANGES_REQUESTED** [review]
Timer doesn't restart when you play a new game(restartin or starting new game from main menu doesn't matter)

**Comment by justino10950** [comment]
If you mean the time on the side of the screen, that is not my code

**Review by winer-bao — APPROVED** [review]
LGTM

**Review by caliangxie — APPROVED** [review]

**Pull request merged**
