### PR TITLE
Checkstyle errors fixed - GameConfig.java

### PR DESCRIPTION
**Pull request by peace-4-you**
Solved new line at end of file
Solved trailing spaces
Solved tab errors

### CODE REVIEW

**Comment by defnoob** [comment]
Could you add Bubble diameter, bubbleoffset(so radius), rowOffset(defined somewhere as (double) diameter * Math.tan(60) + bubbleOffset + 2) along with width/height of at least arena(and it's xPos).

**Comment by peace-4-you** [comment]
> Could you add Bubble diameter

Bubble diameter can already be accessed with Bubble.DIAMETER (it is a static variable).
Or do you want to move that out of the Bubble class?


> bubbleoffset(so radius)

bubbleOffset/ COLUMN_OFFSET added.


> rowOffset(defined somewhere as (double) diameter * Math.tan(60) + bubbleOffset + 2)

ROW_OFFSET added. 


> with width/height of at least arena(and it's xPos).

So add ARENA_WIDTH, ARENA_HEIGH, ARENA_XPOS ? 
and ARENA_YPOS?

**Comment by mauricewillemsen** [comment]
Looks good

**Comment by defnoob** [comment]
LGTM

**Pull request merged**
